### ISSUE TITLE
Remove snkmail.com

### ISSUE THREAD

**Issue by cantelope** [martenson/disposable-email-domains#118]
Please remove snkmail.com. Although it started out as a disposable email service (sneakemail.com), snkmail.com is a paid-subscription service for generating **long-lived unique** email addresses for identifying spam from website registrations.

Emails to the generated address is forwarded to the subscriber with the email tagged so that he knows which email it was sent to, and with the From address altered so that replies go back via snkmail servers and to the original sender. So this is really a service for identifying spam from websites, and not for generating disposable emails.

**Comment by deguif** [comment]
Hi @cantelope 

Thanks for the explanation.
Could you make a PR, for moving the `snkmail.com` domain from blacklist to whitelist?

**Comment by cantelope** [comment]
I've never done this before, so please let me know if I did something wrong.

**Comment by martenson** [comment]
Thank you for the contribution @cantelope and sorry for the inconvenience.
