### ISSUE TITLE
payperex2.com

### ISSUE THREAD

**Issue by ar-anvd** [martenson/disposable-email-domains#129]
Hello. Can't find if emails from this domain are disposable or not. Someone can give it a look?

**Comment by martenson** [comment]
I don't know, there are some clues that is but I am not sure. See: https://duckduckgo.com/?q=payperex2

**Comment by ar-anvd** [comment]
@martenson as I expected, yes it is. See https://temp-mail.org/en/option/change/

**Comment by martenson** [comment]
@ar-anvd added, thanks!
