### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by Pascal76** [martenson/disposable-email-domains#135]
Hello

are you sure about onet.pl ?

Pascal

**Comment by martenson** [comment]
Seems like a valid email service, are you familiar with it? Can you check it please(in case you speak Polish)?

**Comment by martenson** [comment]
![screenshot 2017-11-27 10 46 42](https://user-images.githubusercontent.com/1814954/33275209-45a60dbc-d360-11e7-9d8f-d61d7d2cc0ce.png)

**Comment by martenson** [comment]
looks legit, I removed it, thanks @Pascal76
