### ISSUE TITLE
Remove entries that are suffixes

### ISSUE THREAD

**Issue by Hendikins** [martenson/disposable-email-domains#137]
Upon casual inspection of the list I found various entries that are part of the [Public Suffix List](https://publicsuffix.org/) - this is probably not an exhaustive list:
id.au - Individuals who are Australian citizens/residents
com.ar - Companies and individuals resident in Argentina
edu.my -  Malaysian educational organisations
edu.sg -  Singaporean educational organisations
nom.za - Personal names (South Africa)

These and any other items that are recognised suffixes should be removed from the list.

**Comment by deguif** [comment]
Hi @Hendikins 

Thanks for taking time to improve this list.
A PR would be very welcome regarding the issue you pointed out.

**Comment by martenson** [comment]
@Hendikins thanks for the idea, I have implemented an automatic check in the PR linked above and removed all the domains found in that list you linked.
