### ISSUE TITLE
Did you know?

### ISSUE THREAD

**Issue by pjebs** [martenson/disposable-email-domains#142]
Did you know that all gmail addresses disregards periods.

*You can have any combination of dots in between the letters and it will just work.

* But more relevant to this, you can add "+XXX" to any valid gmail address to make it disposable.

i.e. `peter.smith+disposable@gmail.com`

**Comment by deguif** [comment]
Yes I think we all know. Thanks for your attention ;)
But a gmail address has better chance to be a valid email than temporary mail providers.

**Comment by martenson** [comment]
@pjebs thanks for sharing. I wouldn't call `email+sdsfsd@gmail.com` disposable per se, it still arrives in the same mailbox, but is easier to filter/label/block. 

I think we are still not gonna add @gmail.com to blacklist quite yet ;)
