### ISSUE TITLE
Another for the list

### ISSUE THREAD

**Issue by jq1106** [martenson/disposable-email-domains#145]
Getting a lot of spam accounts from send22u.info

**Comment by deguif** [comment]
Hi @jq1106 Would you mind making a PR?

**Comment by OhArentYouCutenot** [comment]
Why not learn how to throttle signup abuse instead of this blacklisting frippery?

**Comment by jq1106** [comment]
Because a captcha does nothing for someone changing ip’s, clearing browser data, and using a different email to signup for a 2nd account to get another free trial.

**Comment by martenson** [comment]
added in the commit linked above, the rest of the domains you linked were already in, thanks @jq1106
