### ISSUE TITLE
anonymousspeech.com and its anon domains

### ISSUE THREAD

**Issue by C0nw0nk** [martenson/disposable-email-domains#148]
It is a service to create a account with no verification actions required to recieve disposable emails then delete your account when ever you wish.

https://www.anonymousspeech.com/registration.aspx

> Registration at anonymousSpeech.com is completely anonymous.  
> 
> No sign-up confirmation needed
> Hashed encrypted pseudonym (userid) and password
> No email address needed (optional) 
> No IP logging
> Anonymous IP
> Clean Email Header
> SSL Encryption
> Erase Account
> Offshore Server

Users create accounts send and receive emails then delete their accounts allowing another user to use the same address to perform the same actions all of what is disposable and untraceable and has no limits or authentication / checks to prevent users having multiple accounts etc. (Anonymous disposable email account service)

Domains I am aware of.
```
vistomail.com
anonymousspeech.com
```

There may be more.

**Comment by martenson** [comment]
I think this does not look as disposable but rather as a service that aims for anonymity. Main features that disqualify it from being disposable are account password protection and no automatic account deletion.

**Comment by Mubelotix** [comment]
Lol these were the services Satoshi Nakamoto used to stay anonymous in 2008

**Comment by usernameisJim** [comment]
Happy Halloween and Bitcoin Whitepaper day! :jack_o_lantern:
