### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by flayspammers** [martenson/disposable-email-domains#173]
So you won't allow signup from a disposable email address service?  

oh noes!

What will I do?

Gee, maybe I'll treat a non-listed email service as disposable.

And why would I do that?

BECAUSE

the kind of cretinous fops who blacklist self-protection services are typically the scum bent on spamming me - a behavior I will vociferously resist.

YOU FAIL

Your policy is INANITY

**Comment by elliotjreed** [comment]
@flayspammers This is just a list, it is not in itself blocking anything. For example, I use this on an ecommerce platform as part of many indicators as to potentially fraudulent orders, I do not use it to block anyone from anything. So far it has proved highly beneficial.

**Comment by di** [comment]
@flayspammers I had totally forgotten that I wanted to add about 100 new domains to this list, but then this issue showed up in my inbox, [so thanks very much for the reminder!](https://github.com/martenson/disposable-email-domains/pull/174)

**Comment by martenson** [comment]
@flayspammers I believe spam is a function of convenience, every small hurdle on the side of spammer and every small tool on the side of the target user/platform can help prevent it.

Also, thanks for signing up for a github account for the sole purpose of posting such issues. May your future contributions to the open source be more fruitful. You wouldn't want to create an account just for *spamming* repos you don't like, would you?

@elliotjreed @di you two made my day, thanks
