### ISSUE TITLE
Questionable entry

### ISSUE THREAD

**Issue by one23** [martenson/disposable-email-domains#18]
Why would FastMail.fm be on this list (introduced with pull req. #13) ?  It seems rather odd to me for someone to use a paid email service for a disposable/temporary email.

**Comment by martenson** [comment]
@one23 Thanks for bringing this up. I agree that this entry is questionable and also think that we need to be really careful about not blacklisting trustworthy domains. I added all their domains to the whitelist with this commit: https://github.com/martenson/disposable-email-domains/commit/00f22f47e2f52474ef890a05fcbaeaa21699cd61
Thanks again!

**Comment by one23** [comment]
No problem, and thanks for the quick response!
