### ISSUE TITLE
Disposable domains from temp-mail.org

### ISSUE THREAD

**Issue by mrpavlikov** [martenson/disposable-email-domains#180]
temp-mail.org provides mailboxes in different domains:

* 1thecity.biz
* acucre.com
* hiltonvr.com
* bnote.com
* nyrmusic.com
* oranek.com
* pachilly.com
* patonce.com
* rupayamail.com
* sandcars.net
* tryzoe.com
* zdenka.net

Got these ones by opening https://temp-mail.org/api/ in private tab multiple times, you can see the domain in the header. Probably should register app and try to get more with API, but these ones I got so far.

![image](https://user-images.githubusercontent.com/6112323/48140042-070e3980-e2b9-11e8-8990-76127ec4404e.png)

**Comment by martenson** [comment]
@mrpavlikov Would you mind creating a pull request with these?

**Comment by mrpavlikov** [comment]
@martenson got it done. Btw I had a bit of trouble with locale, Ubuntu 18.10 appears to have this one empty, so I had to set it manually, otherwise all the order was ruined. Maybe you should add this to your contributing guide.

```
export LC_ALL=C
```
