### ISSUE TITLE
Remove Sudo-related domains

### ISSUE THREAD

**Issue by rbholland** [martenson/disposable-email-domains#192]
I work for a company which runs [MySudo](https://itunes.apple.com/us/app/mysudo/id1237892621?mt=8), an app on the iOS App Store that allows users to create private emails and phone numbers. We own the following domains, which are in your disposable-email-domains repo:

sudolife.me
sudolife.net
sudomail.biz
sudomail.com
sudomail.net
sudoverse.com
sudoverse.net
sudoweb.net
sudoworld.com
sudoworld.net

We have made improvements to our app to limit the disposability of our email addresses (only paying users are allowed to use the app, we are working to limit the amount of email resets, etc.). Additionally, we have elaborate fraud monitoring, ensuring that our users are not spamming others. A significant amount of our users are reporting that their emails are getting blocked. We are working to clear our name from multiple blacklist providers, and noticed that several email providers rely on your repo. Can we work with you to remove our domains from your list of disposable email domains?

**Comment by martenson** [comment]
@rbholland I agree that your service does not qualify as disposable at the moment. Would you mind creating a pull request removing your domains?

**Comment by martenson** [comment]
closed via https://github.com/martenson/disposable-email-domains/pull/193
