### ISSUE TITLE
PHP Package

### ISSUE THREAD

**Issue by elliotjreed** [martenson/disposable-email-domains#201]
Many thanks for your work on this list again - it's still proving highly useful!

I noticed a couple of people asking questions about PHP integration, so I've knocked-up a little package people can use and install via Composer.

I'll look at finding a nice way of keeping it in-sync with this repository.

https://packagist.org/packages/elliotjreed/disposable-emails-filter

https://github.com/elliotjreed/disposable-emails-filter-php

**Comment by di** [comment]
@elliotjreed You may what to look at what I'm doing [here](https://github.com/di/disposable-email-domains) with the Python package -- it's auto-upgrading on a daily basis.

**Comment by elliotjreed** [comment]
@di That looks perfect, I'll implement that sort of thing - is this run on a Travis schedule?

**Comment by di** [comment]
@elliotjreed It uses [Travis Cron Jobs](https://docs.travis-ci.com/user/cron-jobs/) to run daily.
