### ISSUE TITLE
Restore this domain

### ISSUE THREAD

**Issue by ali654** [martenson/disposable-email-domains#212]
Sir Please
siftportal.ru
i have created a maxbounty account on this domain and my account is blocked i want to check my mail i don't have any other option.
i work hard to earn money and i have more than 100$ in this account
kindly sir restore this domain for one day
Thanks
this is a huge help for me
Thanks

**Comment by martenson** [comment]
@ali654 You have to contact maxbounty for that to work out, it is their choice.
