### ISSUE TITLE
Domains used by temp-mail.org

### ISSUE THREAD

**Issue by hjr265** [martenson/disposable-email-domains#217]
```
temp-link.net
4nextmail.com
coin-host.net
247web.net
free-temp.net
itfast.net
mail-card.net
net1mail.com
tympe.net
web-inc.net
```

Source: https://temp-mail.org/en/change

I was trying to make a pull request for this. But, while following the contribution guidelines, running the two commands seemed to move some of the existing domains around in the disposable_email_blocklist.conf file. 

![image](https://user-images.githubusercontent.com/348107/65389779-54818100-dd7b-11e9-8cce-06b63cb05134.png)

**Comment by martenson** [comment]
@hjr265 It seems your system has different implementation/version of `sort`, I've pushed your suggestions in the commit linked above, thanks!
