### ISSUE TITLE
Is hushmail really disposable?

### ISSUE THREAD

**Issue by rogerkk** [martenson/disposable-email-domains#47]
First of all: Thanks for maintaining this list. It's very useful!

I've noticed a couple of hits on my side with emails from hushmail.com and hush.ai. As I looked into this, I started wondering if hushmail really _is_ disposable email?

It seems to me you actually need to register an account, and I find no trace of the accounts being temporary or being able to send emails without registering.

The closest I get is [this page](https://www.hushmail.com/personal/) mentioning the ability to set up multiple aliases on the nym.hush.com domain, but you'd still need an account.

**Comment by martenson** [comment]
you are right, this service seems legit, I will whitelist them 
thank you @rogerkk !
