### ISSUE TITLE
domain suggestion

### ISSUE THREAD

**Issue by changkun** [martenson/disposable-email-domains#54]
`zasod.com` should be on the list.

**Comment by martenson** [comment]
I cannot see any service running on it. Do you have justification for blacklisting it @changkun?

**Comment by martenson** [comment]
thanks for the tip @changkun

**Comment by changkun** [comment]
@martenson `zasod.com` email generated by `10minutemail.net`, which is already on the list, and somehow also used by **`10minutemail.org`(not on the list)**. Their temp email usually change domain per 45 days, now you can check the website and **`ploae.com`(not on the list)** is used at present.
