### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by szepeviktor** [martenson/disposable-email-domains#84]
`< disposable_email_blacklist.conf xargs -n 1 host -t MX` reveals that

- there are domain with such MX-s as `aspmx.l.google.com.`  (http://www.drevo.si/)
- or parked domains (NS is ns1.dnparking.com.)
- or have a new registrant  (http://www.emil.com/)
- or expired
- or having no Mx at all

Please advise.

**Comment by szepeviktor** [comment]
One solution would be to use Travis CI:

1. Is it a confirmed disposable email domain?
1. Is it registered? - whois
1. Does it have an NS? - root servers
1. Does it have an MX - DNS
1. Are **all** of the MX-s on our MX whitelist?

**Comment by martenson** [comment]
These are great ideas. I am not that educated in domain system - with no MX record can the domain be used for mailing in any way?

**Comment by szepeviktor** [comment]
> with no MX record can the domain be used for mailing in any way?

Of course not.

**Comment by martenson** [comment]
@szepeviktor So I guess good first step would be to move domains with no MX record out of the list. Something like `discontinued_domains.conf`.

**Comment by chafreaky** [comment]
Mhmm, what about people who use this list to prune databases from disposable email addresses, both old and current? Most disposable email providers have a 45 days sunset policy and the domains are then dropped after that time. Should they not be listed anymore?

**Comment by martenson** [comment]
@chafreaky That is a use case that would be covered by transferring the non-existent-MX domains to `discontinued_domains.conf` - would it not?

**Comment by szepeviktor** [comment]
This issue is more about some kind of quality control, keeping thing up-to-date.

**Comment by martenson** [comment]
@szepeviktor To be frank I think non-existent MX entry does not make (former) disposable domain trustworthy per se.

**Comment by chafreaky** [comment]
Definitely not. And a discontinued file would work. We'd have to update the
readme to mention the possibility of including both lists when pruning.

**Comment by ereli** [comment]
Have a look at https://github.com/ereli/disposable-email-domains/tree/validate 
you can run python  `./validate_dns.py |awk -F" - " '{print $2 }'|sort|uniq -c` 
and find out how many domains are no longer actively used.  I should  probably retry on NoAnswer, but these are the basic numbers I've got: 
```
1355  MX found
49  no resolver NS servers found
384  non existent domain
391 NoAnswer
```

**Comment by ScottyTM** [comment]
Domains without an MX can still receive mails. The MTA will try the A record to deliver mails to this domain.

**Comment by szepeviktor** [comment]
> The MTA will try the A record to deliver mails to this domain.

Could you link the reference of this?

**Comment by ScottyTM** [comment]
https://en.wikipedia.org/wiki/MX_record#History_of_fallback_to_address_record

**Comment by szepeviktor** [comment]
Thank you.

> In January 1986, RFC 973 and RFC 974 deprecated the MD and MF records, replaced them with MX, and defined the MX lookup with fallback to A.

I've ran through the two RFC-s and found no traces of the mentioned fallback.

**Comment by ScottyTM** [comment]
> The lookup first attempts to locate an MX record associated with the name.  If a CNAME record is 
> found, the resulting name is processed as if it were the initial name.  If a non-existent domain error is
>  returned, this situation MUST be reported as an error.  If a temporary error is returned, the mess age > MUST be queued and retried later (see Section 4.5.4.1).  If an empty list of MXs is returned, the  
> address is treated as if it was associated with an implicit MX RR, with a preference of 0, pointing to that > host.  If MX records are present, but none of them are usable, or the implicit MX is unusable, this 
> situation MUST be reported as an error.

from https://tools.ietf.org/html/rfc5321#section-5

**Comment by szepeviktor** [comment]
Thank you!

I think it is not implemented in modern MTA-s.

**Comment by ScottyTM** [comment]
Sorry, but it seems you have no idea how mail works. It's been the standard for over 30 years. Every major implements it as it is in the RFC as quoted above.

**Comment by martenson** [comment]
> Domains without an MX can still receive mails. The MTA will try the A record to deliver mails to this domain.

Thanks for the info @ScottyTM, this complicates things a bit further for this issue.

**Comment by ssjunior** [comment]
@ScottyTM is right. If there is no MX, the A will be used as fallback.

**Comment by marcelstoer** [comment]
In a way this is a duplicate of #58.

**Comment by szepeviktor** [comment]
Yes.
