### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by ar-anvd** [martenson/disposable-email-domains#92]
haydoo.com from here https://temp-mail.org/en/

yordanmail.cf from here https://mytemp.email/

mailna.co from here https://www.mohmal.com

aoeuhtns.com from here https://www.emailondeck.com

mvrht.net from here https://10minutemail.com/

**Comment by Alfinator1** [comment]
hezll.com from https://mytemp.email

**Comment by no1youknowz** [comment]
nbox.notif.me from https://nbox.notif.me

**Comment by nikhil-above** [comment]
deyom.com

**Comment by chafreaky** [comment]
Please submit a PR. :)

It takes just a bit more time than leaving a comment and helps everyone out, including you!

**Comment by martenson** [comment]
added in https://github.com/martenson/disposable-email-domains/pull/105
